from __future__ import annotations

from .domain.base import DomainModel
from .domain.case import Actor, ActorRole, CaseKind, CaseMetadata, Party, PartySide
from .domain.case_intelligence import (
    AnalyzerDiagnostic,
    CaseGap,
    CaseGapType,
    CaseGraph,
    CaseGraphEdge,
    CaseGraphEdgeType,
    CaseGraphNode,
    CaseGraphNodeType,
    CaseIntelligenceReport,
    ContradictionGraph,
    ContradictionRecord,
    ContradictionType,
    DisputeStatus,
    EvidenceGraph,
    EvidenceRelationship,
    EvidenceRelationshipType,
    MaterialFactMap,
    MaterialFactRecord,
    ProofStatus,
    TimelineGraph,
    WitnessKnowledgeGraph,
    WitnessKnowledgeRelationship,
)
from .domain.evidence import EvidenceItem, Fact
from .domain.ids import (
    ActorId,
    CaseId,
    ContradictionId,
    ElementId,
    EvidenceId,
    FactId,
    KnowledgeAtomId,
    MatterId,
    ObjectiveId,
    PartyId,
    WitnessId,
)
from .domain.legal import ClaimOrCharge, LegalElement
from .domain.simulation_truth import (
    CoachingReference,
    ExpectedContradiction,
    PrivateSimulationTruth,
)
from .domain.trial import (
    AuthoredCaseTemplate,
    CompiledCasePackage,
    DerivedCaseIntelligence,
    TrialRuntimeState,
)
from .domain.visibility import VisibilityScope
from .domain.witnesses import KnowledgeAtom, Witness

__all__ = [
    "Actor",
    "ActorId",
    "ActorRole",
    "AnalyzerDiagnostic",
    "AuthoredCaseTemplate",
    "CaseGap",
    "CaseGapType",
    "CaseGraph",
    "CaseGraphEdge",
    "CaseGraphEdgeType",
    "CaseGraphNode",
    "CaseGraphNodeType",
    "CaseId",
    "CaseIntelligenceReport",
    "CaseKind",
    "CaseMetadata",
    "ClaimOrCharge",
    "CoachingReference",
    "CompiledCasePackage",
    "ContradictionGraph",
    "ContradictionId",
    "ContradictionRecord",
    "ContradictionType",
    "DerivedCaseIntelligence",
    "DisputeStatus",
    "DomainModel",
    "ElementId",
    "EvidenceGraph",
    "EvidenceId",
    "EvidenceItem",
    "EvidenceRelationship",
    "EvidenceRelationshipType",
    "ExpectedContradiction",
    "Fact",
    "FactId",
    "KnowledgeAtom",
    "KnowledgeAtomId",
    "LegalElement",
    "MaterialFactMap",
    "MaterialFactRecord",
    "MatterId",
    "ObjectiveId",
    "Party",
    "PartyId",
    "PartySide",
    "PrivateSimulationTruth",
    "ProofStatus",
    "TimelineGraph",
    "TrialRuntimeState",
    "VisibilityScope",
    "Witness",
    "WitnessId",
    "WitnessKnowledgeGraph",
    "WitnessKnowledgeRelationship",
]
