from __future__ import annotations

from .domain.base import DomainModel
from .domain.case import Actor, ActorRole, CaseKind, CaseMetadata, Party, PartySide
from .domain.case_intelligence import (
    AnalyzerDiagnostic,
    CaseGap,
    CaseGapType,
    CaseGraph,
    CaseGraphEdge,
    CaseGraphEdgeType,
    CaseGraphNode,
    CaseGraphNodeType,
    CaseIntelligenceReport,
    ContradictionGraph,
    ContradictionRecord,
    ContradictionType,
    DisputeStatus,
    EvidenceGraph,
    EvidenceRelationship,
    EvidenceRelationshipType,
    MaterialFactMap,
    MaterialFactRecord,
    ProofStatus,
    TimelineGraph,
    WitnessKnowledgeGraph,
    WitnessKnowledgeRelationship,
)
from .domain.evidence import EvidenceItem, Fact
from .domain.events import CourtroomEvent, CourtroomEventType
from .domain.ids import (
    ActorId,
    CaseId,
    ContradictionId,
    ElementId,
    EvidenceId,
    FactId,
    KnowledgeAtomId,
    MatterId,
    ObjectiveId,
    PartyId,
    WitnessId,
)
from .domain.legal import ClaimOrCharge, LegalElement
from .domain.procedure import (
    ActionType,
    AnswerValidationStatus,
    EvidenceAdmissionRecord,
    EvidenceAdmissionStatus,
    ExaminationMode,
    ObjectionRecord,
    ObjectionStatus,
    PhaseTransitionRecord,
    ProcedureState,
    ProcedureValidationResult,
    RulingOutcome,
    RulingRecord,
    TrialPhase,
)
from .domain.simulation_truth import (
    CoachingReference,
    ExpectedContradiction,
    PrivateSimulationTruth,
)
from .domain.strategy import (
    CaseTheory,
    EvidencePlan,
    ObjectiveRuntimeState,
    ObjectiveStatus,
    OpponentRiskRecord,
    PartyStrategy,
    StrategicObjective,
    StrategyNote,
    StrategyValidationRecord,
    StrategyValidationStatus,
    WitnessPlan,
)
from .domain.trial import (
    AuthoredCaseTemplate,
    CompiledCasePackage,
    DerivedCaseIntelligence,
    TrialRuntimeState,
)
from .domain.visibility import VisibilityScope
from .domain.witnesses import KnowledgeAtom, Witness

__all__ = [
    "Actor",
    "ActorId",
    "ActorRole",
    "ActionType",
    "AnalyzerDiagnostic",
    "AnswerValidationStatus",
    "AuthoredCaseTemplate",
    "CaseGap",
    "CaseGapType",
    "CaseGraph",
    "CaseGraphEdge",
    "CaseGraphEdgeType",
    "CaseGraphNode",
    "CaseGraphNodeType",
    "CaseId",
    "CaseIntelligenceReport",
    "CaseKind",
    "CaseMetadata",
    "CaseTheory",
    "ClaimOrCharge",
    "CoachingReference",
    "CompiledCasePackage",
    "ContradictionGraph",
    "ContradictionId",
    "ContradictionRecord",
    "ContradictionType",
    "CourtroomEvent",
    "CourtroomEventType",
    "DerivedCaseIntelligence",
    "DisputeStatus",
    "DomainModel",
    "ElementId",
    "EvidenceAdmissionRecord",
    "EvidenceAdmissionStatus",
    "ExaminationMode",
    "EvidenceGraph",
    "EvidenceId",
    "EvidenceItem",
    "EvidencePlan",
    "EvidenceRelationship",
    "EvidenceRelationshipType",
    "ExpectedContradiction",
    "Fact",
    "FactId",
    "KnowledgeAtom",
    "KnowledgeAtomId",
    "LegalElement",
    "MaterialFactMap",
    "MaterialFactRecord",
    "MatterId",
    "ObjectiveId",
    "ObjectiveRuntimeState",
    "ObjectiveStatus",
    "ObjectionRecord",
    "ObjectionStatus",
    "OpponentRiskRecord",
    "Party",
    "PartyId",
    "PartySide",
    "PartyStrategy",
    "PhaseTransitionRecord",
    "ProcedureState",
    "ProcedureValidationResult",
    "PrivateSimulationTruth",
    "ProofStatus",
    "RulingOutcome",
    "RulingRecord",
    "StrategicObjective",
    "StrategyNote",
    "StrategyValidationRecord",
    "StrategyValidationStatus",
    "TimelineGraph",
    "TrialPhase",
    "TrialRuntimeState",
    "VisibilityScope",
    "Witness",
    "WitnessId",
    "WitnessKnowledgeGraph",
    "WitnessKnowledgeRelationship",
    "WitnessPlan",
]
